#!/usr/bin/env bash
#
# setup-dev.sh -- Ubuntu bootstrap for C# / .NET 8 + Tesseract development
# Run with:  sudo bash setup-dev.sh  [devuser]  [public-ssh-key(optional)]
# Example:   sudo bash setup-dev.sh fgama "$(cat ~/.ssh/id_ed25519.pub)"

set -euo pipefail

########################
# 1. ARGUMENTS & VARS  #
########################
DEVUSER=${1:-devuser}
SSH_KEY=${2:-}                  # optional public key string
SDK_MAJOR=8                     # .NET SDK major (8 = .NET 8 LTS)
ARCH=$(dpkg --print-architecture)   # usually amd64 in x86_64 Ubuntu
LIB_DIR="/usr/lib/${ARCH}-linux-gnu"

########################
# 2. USER & SUDO SETUP #
########################
# if ! id "${DEVUSER}" &>/dev/null; then
#   echo "[+] Creating user '${DEVUSER}'..."
#   adduser --disabled-password --gecos "" "${DEVUSER}"
# fi
# echo "[+] Adding '${DEVUSER}' to sudoers (NOPASSWD)..."
# usermod -aG sudo "${DEVUSER}"
# echo "${DEVUSER} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${DEVUSER}
# chmod 0440 /etc/sudoers.d/${DEVUSER}

# Optional: install SSH key
if [[ -n "${SSH_KEY}" ]]; then
  echo "[+] Installing SSH public key for ${DEVUSER}"
  mkdir -p /home/${DEVUSER}/.ssh
  echo "${SSH_KEY}" >/home/${DEVUSER}/.ssh/authorized_keys
  chmod 600 /home/${DEVUSER}/.ssh/authorized_keys
  chown -R ${DEVUSER}:${DEVUSER} /home/${DEVUSER}/.ssh
fi

###############################
# 3. FIX DNS /etc/resolv.conf #
###############################
# echo "[+] Overwriting /etc/resolv.conf with public DNS servers..."
# cat >/etc/resolv.conf <<EOF
# # Generated by setup-dev.sh
# nameserver 1.1.1.1
# nameserver 8.8.8.8
# options edns0
# EOF
# chmod 0644 /etc/resolv.conf
# chattr +i /etc/resolv.conf   # make immutable to stop NetworkManager overwrite

########################
# 4. APT PREP & UPDATE #
########################
echo "[+] Updating apt and basic tooling..."
apt-get update -y
apt-get install -y --no-install-recommends \
  software-properties-common apt-transport-https ca-certificates gnupg lsb-release

########################
# 5. INSTALL .NET SDK  #
########################
echo "[+] Adding Microsoft package feed..."
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor \
  -o /usr/share/keyrings/microsoft.gpg
echo "deb [arch=${ARCH} signed-by=/usr/share/keyrings/microsoft.gpg] \
  https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main" \
  >/etc/apt/sources.list.d/microsoft-prod.list
apt-get update -y
echo "[+] Installing .NET ${SDK_MAJOR}.0 SDK & Runtimes..."
apt-get install -y "dotnet-sdk-${SDK_MAJOR}.0" "aspnetcore-runtime-${SDK_MAJOR}.0"

##################################
# 6. Tesseract 5 + Leptonica 1.82 #
##################################
echo "[+] Installing Tesseract 5 + Leptonica 1.82..."
apt-get install -y --no-install-recommends \
  tesseract-ocr tesseract-ocr-por libtesseract-dev libleptonica-dev

#########################################
# 7. Charles-W wrapper symlink shim     #
#########################################
echo "[+] Creating symlinks for Charles-W wrapper expectations..."
mkdir -p /usr/local/lib
ln -sf "${LIB_DIR}/liblept.so.5"       /usr/local/lib/libleptonica-1.82.0.so
ln -sf "${LIB_DIR}/libtesseract.so.5"  /usr/local/lib/libtesseract50.so
ldconfig

#############################
# 8. DEV UTILITIES & EXTRAS #
#############################
echo "[+] Installing common dev tools..."
apt-get install -y --no-install-recommends \
  build-essential git curl wget tmux htop unzip

####################################
# 9. DOTNET ENV / QUALITY OF LIFE  #
####################################
cat >/etc/profile.d/dotnet-env.sh <<'EOF'
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_ROOT=/usr/share/dotnet
export PATH=$PATH:$DOTNET_ROOT/tools
EOF
chmod +x /etc/profile.d/dotnet-env.sh

##################################
# 10. FINISH – SWITCH TO DEVUSER #
##################################
echo "[+] Bootstrap finished! Switching to '${DEVUSER}'."
sudo -iu "${DEVUSER}"
